apiVersion: v1
kind: ConfigMap
metadata:
  name: nutrihub-config
  namespace: nutrihub
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  RabbitMQ__HostName: "rabbitmq-service"
  RabbitMQ__Port: "5672"
  RabbitMQ__UserName: "guest"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  GrpcSettings__InventoryUrl: "http://inventory-service:9090"
  INVENTORY_SERVICE_URL: "http://inventory-service:5004/api/inventory"