services:
  # DATABASES
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "NutriHub@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "NutriHub@123" -Q "SELECT 1" -b -o /dev/null -No
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: NutriHubOrderDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NutriHub@123
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: NutriHub@123
      MYSQL_DATABASE: NutriHubInventoryDb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pNutriHub@123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  # MESSAGE BROKER
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # SERVICES
  identity-service:
    build:
      context: ./IdentityService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NutriHubIdentityDb;User Id=sa;Password=NutriHub@123;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy

  catalog-service:
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoConnection=mongodb://mongodb:27017
      - MongoDB__DatabaseName=NutriHubCatalogDb
      - GrpcSettings__InventoryUrl=http://inventory-service:9090
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./OrderService/order-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/NutriHubOrderDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=NutriHub@123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - INVENTORY_SERVICE_URL=http://inventory-service:5004/api/inventory
    depends_on:
      - postgres
      - rabbitmq
      - inventory-service
      - notification-service

  inventory-service:
    build:
      context: ./InventoryService/inventory-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/NutriHubInventoryDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=NutriHub@123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy

  api-gateway:
    build:
      context: ./NutriHub.ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - identity-service
      - catalog-service
      - order-service
      - inventory-service
      - notification-service
