apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: nutrihub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: selmab30/nutrihub-identity:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: ASPNETCORE_URLS
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service;Database=NutriHubIdentityDb;User Id=sa;Password=NutriHub@123;TrustServerCertificate=True"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: nutrihub
spec:
  selector:
    app: identity-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP