apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: nutrihub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: selmab30/nutrihub-inventory:latest
          ports:
            - containerPort: 5004
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/NutriHubInventoryDb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: db-password
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: rabbitmq-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: nutrihub
spec:
  selector:
    app: inventory-service
  ports:
    - name: rest
      port: 5004
      targetPort: 5004
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP