apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: nutrihub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: selmab30/nutrihub-order:latest
          ports:
            - containerPort: 5003
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/NutriHubOrderDb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: db-password
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: SPRING_RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: SPRING_RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nutrihub-secrets
                  key: rabbitmq-password
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: INVENTORY_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: nutrihub
spec:
  selector:
    app: order-service
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP