apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: nutrihub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: selmab30/nutrihub-gateway:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Kubernetes"
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: nutrihub-config
                  key: ASPNETCORE_URLS
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: nutrihub
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort